title: Code Documentation
description: A memory sink for all things important
theme: just-the-docs

url: "https://github.com/sonukuldeep/codedocs"

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/favicon.ico"

plugins:
- jekyll-seo-tag

# Aux links for the upper right navigation
aux_links:
  "Visit my GitHub Profile":
  - "https://github.com/sonukuldeep"


