title: My Doc Website
description: A memory hole for all my codes
theme: just-the-docs
baseurl: "sonukuldeep"
url: "github.io"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
