title: My Doc Website
description: A memory hole for all my codes
theme: just-the-docs
baseurl: ""
url: "github.io"
favicon_ico: "/assets/images/favicon.ico"
aux_links:
  Visit My Repo: https://github.com/sonukuldeep
